//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aaru.Archives {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Aaru.Archives.Localization.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Symbian_Name {
            get {
                return ResourceManager.GetString("Symbian_Name", resourceCulture);
            }
        }
        
        internal static string Symbian_Installation_File {
            get {
                return ResourceManager.GetString("Symbian_Installation_File", resourceCulture);
            }
        }
        
        internal static string Symbian_9_1_or_later {
            get {
                return ResourceManager.GetString("Symbian_9_1_or_later", resourceCulture);
            }
        }
        
        internal static string Application_ID_0 {
            get {
                return ResourceManager.GetString("Application_ID_0", resourceCulture);
            }
        }
        
        internal static string UIDs_checksum_0 {
            get {
                return ResourceManager.GetString("UIDs_checksum_0", resourceCulture);
            }
        }
        
        internal static string Symbian_3_or_later {
            get {
                return ResourceManager.GetString("Symbian_3_or_later", resourceCulture);
            }
        }
        
        internal static string Symbian_6_or_later {
            get {
                return ResourceManager.GetString("Symbian_6_or_later", resourceCulture);
            }
        }
        
        internal static string Unknown_EPOC_magic_0 {
            get {
                return ResourceManager.GetString("Unknown_EPOC_magic_0", resourceCulture);
            }
        }
        
        internal static string CRC16_of_header_0 {
            get {
                return ResourceManager.GetString("CRC16_of_header_0", resourceCulture);
            }
        }
        
        internal static string SIS_contains_an_application {
            get {
                return ResourceManager.GetString("SIS_contains_an_application", resourceCulture);
            }
        }
        
        internal static string File_contains_0_languages {
            get {
                return ResourceManager.GetString("File_contains_0_languages", resourceCulture);
            }
        }
        
        internal static string File_contains_0_files_pointer_1 {
            get {
                return ResourceManager.GetString("File_contains_0_files_pointer_1", resourceCulture);
            }
        }
        
        internal static string File_contains_0_requisites {
            get {
                return ResourceManager.GetString("File_contains_0_requisites", resourceCulture);
            }
        }
        
        internal static string Capabilities {
            get {
                return ResourceManager.GetString("Capabilities", resourceCulture);
            }
        }
        
        internal static string Component_version_0_1 {
            get {
                return ResourceManager.GetString("Component_version_0_1", resourceCulture);
            }
        }
        
        internal static string Component_name_for_language_with_code_0_1 {
            get {
                return ResourceManager.GetString("Component_name_for_language_with_code_0_1", resourceCulture);
            }
        }
        
        internal static string Files_for_all_languages {
            get {
                return ResourceManager.GetString("Files_for_all_languages", resourceCulture);
            }
        }
        
        internal static string Files_for_0_language {
            get {
                return ResourceManager.GetString("Files_for_0_language", resourceCulture);
            }
        }
        
        internal static string Requisite_0 {
            get {
                return ResourceManager.GetString("Requisite_0", resourceCulture);
            }
        }
        
        internal static string Required_UID_0_version_1_2 {
            get {
                return ResourceManager.GetString("Required_UID_0_version_1_2", resourceCulture);
            }
        }
        
        internal static string Required_variant_0 {
            get {
                return ResourceManager.GetString("Required_variant_0", resourceCulture);
            }
        }
        
        internal static string Requisite_for_language_0_1 {
            get {
                return ResourceManager.GetString("Requisite_for_language_0_1", resourceCulture);
            }
        }
        
        internal static string SIS_Platform_UID_Series_60_1st_Edition {
            get {
                return ResourceManager.GetString("SIS_Platform_UID_Series_60_1st_Edition", resourceCulture);
            }
        }
        
        internal static string SIS_Platform_UID_Series_60_1st_Edition_Feature_Pack_1 {
            get {
                return ResourceManager.GetString("SIS_Platform_UID_Series_60_1st_Edition_Feature_Pack_1", resourceCulture);
            }
        }
        
        internal static string SIS_Platform_UID_Series_60_2nd_Edition {
            get {
                return ResourceManager.GetString("SIS_Platform_UID_Series_60_2nd_Edition", resourceCulture);
            }
        }
        
        internal static string SIS_Platform_UID_Series_60_2nd_Edition_Feature_Pack_1 {
            get {
                return ResourceManager.GetString("SIS_Platform_UID_Series_60_2nd_Edition_Feature_Pack_1", resourceCulture);
            }
        }
        
        internal static string SIS_Platform_UID_Series_60_2nd_Edition_Feature_Pack_2 {
            get {
                return ResourceManager.GetString("SIS_Platform_UID_Series_60_2nd_Edition_Feature_Pack_2", resourceCulture);
            }
        }
        
        internal static string SIS_Platform_UID_Series_60_2nd_Edition_Feature_Pack_3 {
            get {
                return ResourceManager.GetString("SIS_Platform_UID_Series_60_2nd_Edition_Feature_Pack_3", resourceCulture);
            }
        }
        
        internal static string SIS_Platform_UID_Series_60_3rd_Edition {
            get {
                return ResourceManager.GetString("SIS_Platform_UID_Series_60_3rd_Edition", resourceCulture);
            }
        }
        
        internal static string SIS_Platform_UID_Series_60_3rd_Edition_Feature_Pack_1 {
            get {
                return ResourceManager.GetString("SIS_Platform_UID_Series_60_3rd_Edition_Feature_Pack_1", resourceCulture);
            }
        }
        
        internal static string SIS_Platform_UID_Series_60_3rd_Edition_Feature_Pack_2 {
            get {
                return ResourceManager.GetString("SIS_Platform_UID_Series_60_3rd_Edition_Feature_Pack_2", resourceCulture);
            }
        }
        
        internal static string SIS_Platform_UID_Series_60_5th_Edition {
            get {
                return ResourceManager.GetString("SIS_Platform_UID_Series_60_5th_Edition", resourceCulture);
            }
        }
        
        internal static string SIS_Platform_UID_Symbian_3 {
            get {
                return ResourceManager.GetString("SIS_Platform_UID_Symbian_3", resourceCulture);
            }
        }
        
        internal static string SIS_Platform_UID_Nokia_Belle {
            get {
                return ResourceManager.GetString("SIS_Platform_UID_Nokia_Belle", resourceCulture);
            }
        }
        
        internal static string SIS_Platform_UID_0 {
            get {
                return ResourceManager.GetString("SIS_Platform_UID_0", resourceCulture);
            }
        }
        
        internal static string Archive_options_0 {
            get {
                return ResourceManager.GetString("Archive_options_0", resourceCulture);
            }
        }
        
        internal static string SIS_Platform_UID_UIQ_21 {
            get {
                return ResourceManager.GetString("SIS_Platform_UID_UIQ_21", resourceCulture);
            }
        }
        
        internal static string SIS_Platform_UID_UIQ_30 {
            get {
                return ResourceManager.GetString("SIS_Platform_UID_UIQ_30", resourceCulture);
            }
        }
        
        internal static string SIS_Platform_UID_Nokia_7650 {
            get {
                return ResourceManager.GetString("SIS_Platform_UID_Nokia_7650", resourceCulture);
            }
        }
        
        internal static string SIS_Platform_UID_Series_60_v1_0 {
            get {
                return ResourceManager.GetString("SIS_Platform_UID_Series_60_v1_0", resourceCulture);
            }
        }
        
        internal static string SIS_Platform_UID_Nokia_3650 {
            get {
                return ResourceManager.GetString("SIS_Platform_UID_Nokia_3650", resourceCulture);
            }
        }
        
        internal static string SIS_Platform_UID_Nokia_6600 {
            get {
                return ResourceManager.GetString("SIS_Platform_UID_Nokia_6600", resourceCulture);
            }
        }
        
        internal static string SIS_Platform_UID_Nokia_6630 {
            get {
                return ResourceManager.GetString("SIS_Platform_UID_Nokia_6630", resourceCulture);
            }
        }
        
        internal static string SIS_Platform_UID_SonyEricsson_P80x {
            get {
                return ResourceManager.GetString("SIS_Platform_UID_SonyEricsson_P80x", resourceCulture);
            }
        }
        
        internal static string SIS_Platform_UID_Series_60_v1_1 {
            get {
                return ResourceManager.GetString("SIS_Platform_UID_Series_60_v1_1", resourceCulture);
            }
        }
        
        internal static string SIS_Platform_UID_Nokia_N_Gage {
            get {
                return ResourceManager.GetString("SIS_Platform_UID_Nokia_N_Gage", resourceCulture);
            }
        }
        
        internal static string SIS_Platform_UID_Nokia_9500 {
            get {
                return ResourceManager.GetString("SIS_Platform_UID_Nokia_9500", resourceCulture);
            }
        }
        
        internal static string SIS_Platform_UID_Nokia_9300 {
            get {
                return ResourceManager.GetString("SIS_Platform_UID_Nokia_9300", resourceCulture);
            }
        }
        
        internal static string SIS_Platform_UID_Series_80_2nd_edition {
            get {
                return ResourceManager.GetString("SIS_Platform_UID_Series_80_2nd_edition", resourceCulture);
            }
        }
        
        internal static string SIS_Platform_UID_Siemens_SX1 {
            get {
                return ResourceManager.GetString("SIS_Platform_UID_Siemens_SX1", resourceCulture);
            }
        }
        
        internal static string SIS_Platform_UID_Nokia_6260 {
            get {
                return ResourceManager.GetString("SIS_Platform_UID_Nokia_6260", resourceCulture);
            }
        }
        
        internal static string SIS_Platform_UID_SonyEricsson_P90x {
            get {
                return ResourceManager.GetString("SIS_Platform_UID_SonyEricsson_P90x", resourceCulture);
            }
        }
        
        internal static string SIS_Platform_UID_Nokia_7710_Series_90 {
            get {
                return ResourceManager.GetString("SIS_Platform_UID_Nokia_7710_Series_90", resourceCulture);
            }
        }
        
        internal static string SIS_Platform_UID_Nokia_7610 {
            get {
                return ResourceManager.GetString("SIS_Platform_UID_Nokia_7610", resourceCulture);
            }
        }
        
        internal static string SIS_Platform_UID_Nokia_6670 {
            get {
                return ResourceManager.GetString("SIS_Platform_UID_Nokia_6670", resourceCulture);
            }
        }
        
        internal static string SIS_Platform_UID_UIQ_20 {
            get {
                return ResourceManager.GetString("SIS_Platform_UID_UIQ_20", resourceCulture);
            }
        }
        
        internal static string SIS_Platform_UID_Nokia_3230 {
            get {
                return ResourceManager.GetString("SIS_Platform_UID_Nokia_3230", resourceCulture);
            }
        }
        
        internal static string SIS_Platform_UID_Nokia_N90 {
            get {
                return ResourceManager.GetString("SIS_Platform_UID_Nokia_N90", resourceCulture);
            }
        }
        
        internal static string SIS_Platform_UID_Nokia_N70 {
            get {
                return ResourceManager.GetString("SIS_Platform_UID_Nokia_N70", resourceCulture);
            }
        }
        
        internal static string SIS_Platform_UID_Nokia_6680 {
            get {
                return ResourceManager.GetString("SIS_Platform_UID_Nokia_6680", resourceCulture);
            }
        }
        
        internal static string SIS_Platform_UID_Nokia_6620 {
            get {
                return ResourceManager.GetString("SIS_Platform_UID_Nokia_6620", resourceCulture);
            }
        }
        
        internal static string SIS_Platform_UID_Nokia_6682 {
            get {
                return ResourceManager.GetString("SIS_Platform_UID_Nokia_6682", resourceCulture);
            }
        }
        
        internal static string SIS_Platform_UID_Nokia_6681 {
            get {
                return ResourceManager.GetString("SIS_Platform_UID_Nokia_6681", resourceCulture);
            }
        }
        
        internal static string SIS_Platform_UID_Nokia_3250 {
            get {
                return ResourceManager.GetString("SIS_Platform_UID_Nokia_3250", resourceCulture);
            }
        }
        
        internal static string SIS_Platform_UID_Nokia_N80 {
            get {
                return ResourceManager.GetString("SIS_Platform_UID_Nokia_N80", resourceCulture);
            }
        }
        
        internal static string SIS_Platform_UID_Nokia_N92 {
            get {
                return ResourceManager.GetString("SIS_Platform_UID_Nokia_N92", resourceCulture);
            }
        }
        
        internal static string SIS_Platform_UID_Nokia_N73 {
            get {
                return ResourceManager.GetString("SIS_Platform_UID_Nokia_N73", resourceCulture);
            }
        }
        
        internal static string SIS_Platform_UID_Nokia_N91 {
            get {
                return ResourceManager.GetString("SIS_Platform_UID_Nokia_N91", resourceCulture);
            }
        }
        
        internal static string SIS_Platform_UID_Nokia_N71 {
            get {
                return ResourceManager.GetString("SIS_Platform_UID_Nokia_N71", resourceCulture);
            }
        }
        
        internal static string SIS_Platform_UID_Nokia_E60 {
            get {
                return ResourceManager.GetString("SIS_Platform_UID_Nokia_E60", resourceCulture);
            }
        }
        
        internal static string SIS_Platform_UID_Nokia_E70 {
            get {
                return ResourceManager.GetString("SIS_Platform_UID_Nokia_E70", resourceCulture);
            }
        }
        
        internal static string SIS_Platform_UID_Nokia_E61 {
            get {
                return ResourceManager.GetString("SIS_Platform_UID_Nokia_E61", resourceCulture);
            }
        }
        
        internal static string Option_0 {
            get {
                return ResourceManager.GetString("Option_0", resourceCulture);
            }
        }
        
        internal static string Name_for_language_0_1 {
            get {
                return ResourceManager.GetString("Name_for_language_0_1", resourceCulture);
            }
        }
        
        internal static string This_file_format_is_not_yet_implemented {
            get {
                return ResourceManager.GetString("This_file_format_is_not_yet_implemented", resourceCulture);
            }
        }
        
        internal static string Found_component_name_for_language_0_at_1_with_a_length_of_2_bytes {
            get {
                return ResourceManager.GetString("Found_component_name_for_language_0_at_1_with_a_length_of_2_bytes", resourceCulture);
            }
        }
        
        internal static string Conditions {
            get {
                return ResourceManager.GetString("Conditions", resourceCulture);
            }
        }
    }
}
