//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aaru.Tui.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aaru.Tui.Localization.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} sectors.
        /// </summary>
        public static string _0_sectors {
            get {
                return ResourceManager.GetString("_0_sectors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASCII          .
        /// </summary>
        public static string ASCII_Text {
            get {
                return ResourceManager.GetString("ASCII.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESC Back.
        /// </summary>
        public static string Back_Header {
            get {
                return ResourceManager.GetString("Back.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelButton_Content {
            get {
                return ResourceManager.GetString("CancelButton.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current sector: .
        /// </summary>
        public static string CurrentSector_Text {
            get {
                return ResourceManager.GetString("CurrentSector.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter destination path:.
        /// </summary>
        public static string DestinationPath_Text {
            get {
                return ResourceManager.GetString("DestinationPath.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination path.
        /// </summary>
        public static string DestinationPath_Watermark {
            get {
                return ResourceManager.GetString("DestinationPath.Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done..
        /// </summary>
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F10 Exit.
        /// </summary>
        public static string Exit_Header {
            get {
                return ResourceManager.GetString("Exit.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exits the application.
        /// </summary>
        public static string ExitApplication_Text {
            get {
                return ResourceManager.GetString("ExitApplication.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attributes:.
        /// </summary>
        public static string FileAttributes_Text {
            get {
                return ResourceManager.GetString("FileAttributes.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation time:.
        /// </summary>
        public static string FileCreationTime_Text {
            get {
                return ResourceManager.GetString("FileCreationTime.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File information.
        /// </summary>
        public static string FileInformation_Text {
            get {
                return ResourceManager.GetString("FileInformation.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last write time:.
        /// </summary>
        public static string FileLastWriteTime_Text {
            get {
                return ResourceManager.GetString("FileLastWriteTime.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length:.
        /// </summary>
        public static string FileLength_Text {
            get {
                return ResourceManager.GetString("FileLength.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode:.
        /// </summary>
        public static string FileMode_Text {
            get {
                return ResourceManager.GetString("FileMode.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filesystem information.
        /// </summary>
        public static string FilesystemInformation_Text {
            get {
                return ResourceManager.GetString("FilesystemInformation.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go back to previous window.
        /// </summary>
        public static string GoBack_Text {
            get {
                return ResourceManager.GetString("GoBack.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to next sector.
        /// </summary>
        public static string GoNextSector_Text {
            get {
                return ResourceManager.GetString("GoNextSector.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to previous sector.
        /// </summary>
        public static string GoPreviousSector_Text {
            get {
                return ResourceManager.GetString("GoPreviousSector.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to the specified sector.
        /// </summary>
        public static string GoSpecifiedSector_Text {
            get {
                return ResourceManager.GetString("GoSpecifiedSector.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F4  GoTo.
        /// </summary>
        public static string GoTo_Header {
            get {
                return ResourceManager.GetString("GoTo.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to path.
        /// </summary>
        public static string GoToPath_Title {
            get {
                return ResourceManager.GetString("GoToPath.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to Sector.
        /// </summary>
        public static string GoToSector_Title {
            get {
                return ResourceManager.GetString("GoToSector.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to the specified path.
        /// </summary>
        public static string GoToSpecifiedPath_Text {
            get {
                return ResourceManager.GetString("GoToSpecifiedPath.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F1  Help.
        /// </summary>
        public static string Help_Header {
            get {
                return ResourceManager.GetString("Help.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Help_Title {
            get {
                return ResourceManager.GetString("Help.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image information.
        /// </summary>
        public static string ImageInformation_Text {
            get {
                return ResourceManager.GetString("ImageInformation.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading file information....
        /// </summary>
        public static string Loading_file_information {
            get {
                return ResourceManager.GetString("Loading_file_information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading filesystems....
        /// </summary>
        public static string Loading_filesystems {
            get {
                return ResourceManager.GetString("Loading_filesystems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading partitions....
        /// </summary>
        public static string Loading_partitions {
            get {
                return ResourceManager.GetString("Loading_partitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F5  Long.
        /// </summary>
        public static string Long_Header {
            get {
                return ResourceManager.GetString("Long.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (Long Mode).
        /// </summary>
        public static string Long_Mode {
            get {
                return ResourceManager.GetString("Long_Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F2  Next.
        /// </summary>
        public static string Next_Header {
            get {
                return ResourceManager.GetString("Next.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offset.
        /// </summary>
        public static string Offset_Text {
            get {
                return ResourceManager.GetString("Offset.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OkButton_Content {
            get {
                return ResourceManager.GetString("OkButton.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partition {0}.
        /// </summary>
        public static string Partition_0 {
            get {
                return ResourceManager.GetString("Partition_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        public static string PartitionDescription_Text {
            get {
                return ResourceManager.GetString("PartitionDescription.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partition information.
        /// </summary>
        public static string PartitionInformation_Text {
            get {
                return ResourceManager.GetString("PartitionInformation.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length:.
        /// </summary>
        public static string PartitionLength_Text {
            get {
                return ResourceManager.GetString("PartitionLength.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string PartitionName_Text {
            get {
                return ResourceManager.GetString("PartitionName.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offset:.
        /// </summary>
        public static string PartitionOffset_Text {
            get {
                return ResourceManager.GetString("PartitionOffset.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheme:.
        /// </summary>
        public static string PartitionScheme_Text {
            get {
                return ResourceManager.GetString("PartitionScheme.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence: .
        /// </summary>
        public static string PartitionSequence_Text {
            get {
                return ResourceManager.GetString("PartitionSequence.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size:.
        /// </summary>
        public static string PartitionSize_Text {
            get {
                return ResourceManager.GetString("PartitionSize.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting sector:.
        /// </summary>
        public static string PartitionStartingSector_Text {
            get {
                return ResourceManager.GetString("PartitionStartingSector.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type:.
        /// </summary>
        public static string PartitionType_Text {
            get {
                return ResourceManager.GetString("PartitionType.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path cannot be empty.
        /// </summary>
        public static string Path_cannot_be_empty {
            get {
                return ResourceManager.GetString("Path_cannot_be_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path does not exist.
        /// </summary>
        public static string Path_does_not_exist {
            get {
                return ResourceManager.GetString("Path_does_not_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid number..
        /// </summary>
        public static string Please_enter_a_valid_number {
            get {
                return ResourceManager.GetString("Please_enter_a_valid_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F3  Prev.
        /// </summary>
        public static string Prev_Header {
            get {
                return ResourceManager.GetString("Prev.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sector number must be less than or equal to {0}..
        /// </summary>
        public static string Sector_number_must_be_less_than_or_equal_to_0 {
            get {
                return ResourceManager.GetString("Sector_number_must_be_less_than_or_equal_to_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter sector number:.
        /// </summary>
        public static string SectorNumber_Text {
            get {
                return ResourceManager.GetString("SectorNumber.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sector number.
        /// </summary>
        public static string SectorNumber_Watermark {
            get {
                return ResourceManager.GetString("SectorNumber.Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F2  ScVw.
        /// </summary>
        public static string SectorViewer_Header {
            get {
                return ResourceManager.GetString("SectorViewer.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sector viewer.
        /// </summary>
        public static string SectorViewer_Text {
            get {
                return ResourceManager.GetString("SectorViewer.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows this help.
        /// </summary>
        public static string ShowHelp_Text {
            get {
                return ResourceManager.GetString("ShowHelp.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle long sector mode.
        /// </summary>
        public static string ToggleLongMode_Text {
            get {
                return ResourceManager.GetString("ToggleLongMode.Text", resourceCulture);
            }
        }
    }
}
